function subf_DisplayFB(windowPtr, STargetPos, fb, correct, patch, crossX, crossY)
% Subfunction to display the feedback

% Display feedback at the location of the selected stimulus
if STargetPos == 1
    shift = -1; % left selected -> shift on the left (reduce pixel number)
else
    shift = 1;  % right selected -> shift on the right (increase pixel number)
end

if correct == 1
    
    % POSITIVE FEEDBACK: TICK
    Screen('DrawLine', windowPtr, fb.ColPosFB, ...
        crossX + shift*patch.cx, ...
        crossY + round(fb.FBsize/2), ...
        crossX + shift*patch.cx + round(fb.FBsize/2), ...
        crossY - round(fb.FBsize/2), 2)
    Screen('DrawLine', windowPtr, fb.ColPosFB, ...
        crossX + shift*patch.cx - round(fb.FBsize/2), ...
        crossY, ...
        crossX + shift*patch.cx, ...
        crossY + round(fb.FBsize/2), 2)
else
    
    % NEGATIVE FEEDBACK: X
    Screen('DrawLine', windowPtr, fb.ColNegFB, ...
        crossX + shift*patch.cx + shift*round(fb.FBsize/2), ...
        crossY - round(fb.FBsize/2), ...
        crossX + shift*patch.cx - shift*round(fb.FBsize/2), ...
        crossY + round(fb.FBsize/2), 2)
    Screen('DrawLine', windowPtr, fb.ColNegFB, ...
        crossX + shift*patch.cx + shift*round(fb.FBsize/2), ...
        crossY + round(fb.FBsize/2), ...
        crossX + shift*patch.cx - shift*round(fb.FBsize/2), ...
        crossY - round(fb.FBsize/2), 2)
end
